select * from CUSTOMERS 
     where country = (select country from suppliers where supplier_number=1)
	 and city =  (select city from suppliers where supplier_number=1)
	 and RIGHT ( postal_code,3)=  (select RIGHT ( postal_code,3)  from suppliers where supplier_number=1)

	 SELECT 
    ORDER_NUMBER,
    UNIT_PRICE * QUANTITY AS TotalAmountBeforeDiscount,
    CASE 
        WHEN UNIT_PRICE * QUANTITY BETWEEN 0 AND 2000 THEN '0%'
        WHEN UNIT_PRICE * QUANTITY BETWEEN 2001 AND 10000 THEN '5%'
        WHEN UNIT_PRICE * QUANTITY BETWEEN 10001 AND 40000 THEN '10%'
        WHEN UNIT_PRICE * QUANTITY BETWEEN 40001 AND 80000 THEN '15%'
        ELSE '20%'
    END AS Discount,
	    CASE 
        WHEN ORDER_NUMBER BETWEEN 10000 AND 10999 THEN 'apply old discount rate'
        ELSE 'apply new discount rate'
    END AS DiscountRateApplicationNote
FROM ORDER_DETAILS
WHERE ORDER_NUMBER BETWEEN 10998 AND 11003;



SELECT 
    S.SUPPLIER_NUMBER,
    S.COMPANY,
    S.ADDRESS,
    S.PHONE
FROM SUPPLIERS s
JOIN PRODUCTS P ON S.SUPPLIER_NUMBER = P.SUPPLIER_NUMBER
JOIN CATEGORIES C ON P.CATEGORY_CODE = C.CATEGORY_CODE
WHERE C.CATEGORY_NAME = 'Beverages';



SELECT C.CUSTOMER_CODE
FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
JOIN ORDER_DETAILS OD ON O.ORDER_NUMBER = OD.ORDER_NUMBER
JOIN PRODUCTS P ON OD.PRODUCT_REF = P.PRODUCT_REF
JOIN CATEGORIES CAT ON P.CATEGORY_CODE = CAT.CATEGORY_CODE
WHERE C.CITY = 'Berlin' AND CAT.CATEGORY_NAME = 'Desserts'

SELECT 
    C.CUSTOMER_CODE,
    C.COMPANY,
    C.PHONE,
    SUM(OD.UNIT_PRICE * OD.QUANTITY * (1 - OD.DISCOUNT)) AS TotalAmount,
    C.COUNTRY
FROM CUSTOMERS C
LEFT JOIN ORDERS O ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
LEFT JOIN ORDER_DETAILS OD ON O.ORDER_NUMBER = OD.ORDER_NUMBER
WHERE C.COUNTRY = 'France'
  AND (O.ORDER_DATE IS NULL OR (YEAR(O.ORDER_DATE) = 1998 
       AND MONTH(O.ORDER_DATE) = 4 
       AND DATENAME(WEEKDAY, O.ORDER_DATE) = 'Monday'))


	   SELECT 
    C.CUSTOMER_CODE,
    C.COMPANY,
    C.PHONE
FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
JOIN ORDER_DETAILS OD ON O.ORDER_NUMBER = OD.ORDER_NUMBER
JOIN PRODUCTS P ON OD.PRODUCT_REF = P.PRODUCT_REF
GROUP BY C.CUSTOMER_CODE, C.COMPANY, C.PHONE
HAVING COUNT(DISTINCT P.PRODUCT_REF) = (SELECT COUNT(*) FROM PRODUCTS);


 
 SELECT 
    C.CUSTOMER_CODE,
    COUNT(O.ORDER_NUMBER) AS NumberOfOrders
FROM CUSTOMERS C
LEFT JOIN ORDERS O ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
WHERE C.COUNTRY = 'France'
GROUP BY C.CUSTOMER_CODE;



SELECT 
    (SELECT COUNT(*) FROM ORDERS WHERE YEAR(ORDER_DATE) = 1996) AS OrdersIn1996,
    (SELECT COUNT(*) FROM ORDERS WHERE YEAR(ORDER_DATE) = 1997) AS OrdersIn1997,
    (SELECT COUNT(*) FROM ORDERS WHERE YEAR(ORDER_DATE) = 1997) - 
    (SELECT COUNT(*) FROM ORDERS WHERE YEAR(ORDER_DATE) = 1996) AS Difference;
